[DSDialogService] fixed hasDialogOpen method
takenet/blip-ds-flutter pull request #140
Opened 2023-05-12 20:24 UTC by leonardogbr

2023-05-12 20:27 UTC, RaulRodrigo06 approved these changes

2023-05-12 21:18 UTC, PaollaLira approved these changes

2023-05-15 12:06 UTC, mpamaro requested changes

2023-05-15 12:06 UTC, mpamaro commented on lib/src/services/ds_dialog.service.dart
> +  }) : context = context ?? Get.overlayContext ?? Get.context!;
```suggestion
  }) : context ??= Get.overlayContext ?? Get.context!;
```

2023-05-15 12:54 UTC, merged