Feature/370399 document select
takenet/blip-ds-flutter pull request #24
Opened 2022-09-26 17:30 UTC by githubdoandre

2022-09-27 11:54 UTC, mpamaro requested changes

2022-09-27 13:35 UTC, githubdoandre commented on lib/src/widgets/chat/ds_image_message_bubble.widget.dart
> +                    options: selectOptions!,
Done

2022-09-27 14:39 UTC, mpamaro approved these changes

2022-09-29 13:16 UTC, leonardogbr approved these changes

2022-09-29 18:25 UTC, closed without merging