Feature/371715 create weblink card
takenet/blip-ds-flutter pull request #49
Opened 2022-11-04 20:43 UTC by PaollaLira

(x) It was possible to take advantage of existing code; 
(x) Comments have been deleted; 
(x) Tested on IOS; 
( ) This is a BugFix; 
( ) Tests were added; 
(x) There is no breakage of existing functionalities; 
- Briefly describe how the test should be done: layout of bubble and test link opening.

2022-11-07 12:16 UTC, githubdoandre commented on lib/src/services/ds_bottom_sheet.service.dart
>  class DSBottomSheetService {
do you create this branche from develop? because this changes is not in develop

2022-11-07 12:18 UTC, jwdutra commented on lib/src/widgets/chat/ds_weblink.widget.dart
> +class DSWeblink extends StatelessWidget {
Write documentation explaining what the widget is for

2022-11-07 12:29 UTC, githubdoandre commented
change you destination branch to develop please

2022-11-07 16:24 UTC, leonardogbr requested changes

2022-11-07 16:24 UTC, leonardogbr commented on lib/src/utils/ds_linkify.util.dart
> +  DSLinkify(String url);
Remove unnecessary constructor.

2022-11-07 16:24 UTC, leonardogbr commented on lib/src/widgets/chat/ds_weblink.widget.dart
> +  final List<DSBorderRadius>? borderRadius;
borderRadius should not be nullable.

2022-11-07 16:24 UTC, leonardogbr commented on lib/src/widgets/chat/ds_weblink.widget.dart
> +      borderRadius: borderRadius!,
Remove the `!`

2022-11-07 16:24 UTC, leonardogbr commented on lib/src/widgets/chat/ds_weblink.widget.dart
> +    final color = style.isLightBubbleBackground(align)
```suggestion
    final isDefaultBubbleColors = style.isDefaultBubbleBackground(widget.align);
    final isLightBubbleBackground = style.isLightBubbleBackground(align);
    
    final color = isLightBubbleBackground
```

2022-11-07 16:24 UTC, leonardogbr commented on lib/src/widgets/chat/ds_weblink.widget.dart
> +            linkColor: align == DSAlign.left
LinkColor have to consider bubble style

```suggestion
            linkColor: isLightBubbleBackground
                  ? isDefaultBubbleColors
                      ? DSColors.primaryNight
                      : DSColors.neutralDarkCity
                  : isDefaultBubbleColors
                      ? DSColors.primaryLight
                      : DSColors.neutralLightSnow
```

2022-11-07 16:24 UTC, leonardogbr commented on lib/src/widgets/chat/ds_weblink.widget.dart
> +                ? DSColors.primaryNight
```suggestion
```

2022-11-07 16:24 UTC, leonardogbr commented on lib/src/widgets/chat/ds_weblink.widget.dart
> +                : DSColors.primaryLight,
```suggestion

```

2022-11-07 16:24 UTC, leonardogbr commented on lib/src/widgets/utils/ds_card.widget.dart
> +// import 'package:blip_ds/src/widgets/chat/ds_weblink.widget.dart';
Remove comment

2022-11-07 16:24 UTC, leonardogbr commented on lib/src/widgets/utils/ds_card.widget.dart
>  import 'package:blip_ds/blip_ds.dart';
Remove blip_ds import. Change this to single file imports

2022-11-08 18:29 UTC, jwdutra approved these changes

2022-11-08 19:45 UTC, leonardogbr approved these changes

2022-11-08 20:38 UTC, merged